# Generated by Django 5.0.7 on 2024-08-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"managed": True, "ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={"managed": True, "ordering": ["-id"]},
        ),
        migrations.AlterModelTable(
            name="chatmessage",
            table="chat_message",
        ),
        migrations.AlterModelTable(
            name="chatroom",
            table="chat_room",
        ),
    ]
