# Generated by Django 5.1 on 2024-08-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'managed': True, 'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='chat_room',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='message_sender',
        ),
    ]
